// Compare two of a candidate's interviews. The DETERMINISTIC half lives here —
// load a compact per-session snapshot from the DB and compute numeric deltas
// (rating, pacing, skips). The QUALITATIVE half (what improved / slipped / to
// focus on) is generated by the LLM in llm/index.ts and degrades gracefully.
import { getSession } from "./db";
import { buildInterviewState } from "./state";
import type { Feedback } from "./types";

// A compact, comparable snapshot of one session.
export interface CompareSide {
  id: string;
  createdAt: string;
  level: string; // "L5 — Senior SWE"
  levelId: string;
  methodology: string; // "STAR"
  rating: number | null; // null until feedback exists
  totalSeconds: number | null; // total time across answered questions
  questionCount: number; // questions actually reached
  skipped: number;
  feedback: Feedback | null;
}

// Numeric deltas, oriented older → newer (positive rating = improved,
// negative pace = faster, negative skipped = fewer skips).
export interface CompareDiff {
  ratingDelta: number | null;
  paceDelta: number | null; // seconds, newer - older
  skippedDelta: number; // newer - older
}

// Build a snapshot from the DB, reusing the same state builder as the rest of
// the app so pacing/skip logic stays single-sourced. Returns null if missing.
export function loadCompareSide(id: string): CompareSide | null {
  const state = buildInterviewState(id);
  const session = getSession(id);
  if (!state || !session) return null;
  return {
    id,
    createdAt: session.created_at,
    level: state.level.name,
    levelId: state.level.id,
    methodology: state.methodology.name,
    rating: state.feedback ? state.feedback.rating : null,
    totalSeconds: state.pacing ? state.pacing.totalSeconds : null,
    questionCount: state.pacing ? state.pacing.perQuestion.length : state.mainQuestionCount,
    skipped: state.skippedCount,
    feedback: state.feedback,
  };
}

// Order two sides oldest-first so deltas read as progress over time.
export function orderByDate(a: CompareSide, b: CompareSide): [CompareSide, CompareSide] {
  return Date.parse(a.createdAt) <= Date.parse(b.createdAt) ? [a, b] : [b, a];
}

export function diffSides(older: CompareSide, newer: CompareSide): CompareDiff {
  return {
    ratingDelta: older.rating != null && newer.rating != null ? newer.rating - older.rating : null,
    paceDelta: older.totalSeconds != null && newer.totalSeconds != null ? newer.totalSeconds - older.totalSeconds : null,
    skippedDelta: newer.skipped - older.skipped,
  };
}
